const data = [
  {
    id: "g5r4ef4",
    name: "shashlik",
    img: "",
    price: "9876",
    description: "shashliklar",
    status: 1,
    quantity: 2,
  },
  {
    id: "g5r4ef4",
    name: "shashlik",
    img: "",
    price: "9876",
    description: "shashliklar",
    status: 1,
    quantity: 2,
  },
  {
    id: "g5r4ef4",
    name: "shashlik",
    img: "",
    price: "9876",
    description: "shashliklar",
    status: 1,
    quantity: 2,
  },
  {
    id: "g5r4ef4",
    name: "shashlik",
    img: "",
    price: "9876",
    description: "shashliklar",
    status: 1,
    quantity: 2,
  },
  {
    id: "g5r4ef4",
    name: "shashlik",
    img: "",
    price: "9876",
    description: "shashliklar",
    status: 1,
    quantity: 2,
  },
  {
    id: "g5r4ef4",
    name: "shashlik",
    img: "",
    price: "9876",
    description: "shashliklar",
    status: 1,
    quantity: 2,
  },
];
